---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
	- common
	- docker
	- transmission-tvshows
	- transmission-movies
	- sonarr
	- radarr
	- ombi
	- plex
	- plexpy
	- jackett
	- rutorrent
	- glances
	- muximux
