---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  # become_user: root
  remote_user: root
  # become: yes
  # become_method: sudo

  roles:
  - common
  - docker
  - fail2ban
  - transmission-tvshows
  - transmission-movies
  - jackett
  - sonarr
  - radarr
  - ombi
  - plex
  - plexpy
  - rutorrent
  - flexget
  - glances
  - muximux
