---
# Create the docker container for Muximux 

- name: Create directories 
  file: 
    path: '/home/docker/muximux/config/www/muximux'
    recurse: yes
    state: directory
    owner: '{{ userid }}'
    group: '{{ groupid }}'
    mode: 0775

- name: Copy config file
  template:
    src: config.j2
    dest: /home/docker/muximux/config/www/muximux/settings.ini.php
    owner: '{{ userid }}'
    group: '{{ groupid }}'
    mode: 0644

- name: Create systemd service
  template:
    src: service.j2
    dest: /etc/systemd/system/muximux.service
    owner: root
    group: root
    mode: 0644

- name: Start service
  systemd:
    name: muximux.service
    state: started
    daemon_reload: yes

- name: Enable service
  systemd:
    name: muximux.service
    enabled: yes
