---
# Create the docker container for Sonarr 

- name: Create directories 
  file: 
    path: '{{ item }}'
    recurse: yes
    state: directory
    owner: '{{ userid }}'
    group: '{{ groupid }}'
    mode: 0775
  with_items:
      - /home/docker/sonarr/downloads
      - /home/docker/sonarr/config:/config
      - /home/docker/sonarr/tvshows:/tv

- name: Create systemd service
  template:
    src: service.j2
    dest: /etc/systemd/system/sonarr.service
    owner: root
    group: root
    mode: 0644

- name: Start service
  systemd:
    name: sonarr.service
    state: started
    daemon_reload: yes
- name: Enable service
  systemd:
    name: sonarr.service
    enabled: yes
