---
# Create the docker container for Fail2Ban

- name: Import docker image
  docker_image: 
    image: superitman/fail2ban

- name: Create directory 
  file: 
    path: '{{ item }}'
    recurse: yes
    state: directory
    owner: '{{ userid }}'
    group: '{{ groupid }}'
    mode: 0775
  with_items:
    - /home/docker/fail2ban/action.d
    - /home/docker/fail2ban/filter.d
   
- name: Copy config files 1/2
  copy: 
    src: '{{ item }}'
    dest: /home/docker/fail2ban/
    owner: '{{ userid }}'
    group: '{{ groupid }}'
    mode: 0644
  with_items:
      - filter.d
      - action.d
      
- name: Copy config files 2/2
  template:
    src: jail.local
    dest: /home/docker/fail2ban/jail.local
    owner: '{{ userid }}'
    group: '{{ groupid }}'
    mode: 0644   
    
- name: Create systemd service
  copy:
    src: fail2ban.service
    dest: /etc/systemd/system/fail2ban.service
    owner: root
    group: root
    mode: 0644

- name: Start service
  systemd:
    name: fail2ban.service
    state: started
    daemon_reload: yes

- name: Enable service
  systemd:
    name: fail2ban.service
    enabled: yes
